pipeline{
    agent any
    stages{
        stage('Buid'){
            steps{

                withCredentials([sshUserPrivateKey(credentialsId: 'my-ssh-key-id', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')]) {
                    sh """ssh -o StrictHostKeyChecking=no -i SSH_KEY ec2-user@13.61.100.59 docker ps
                    """
                }
            }
        }
    }
}